// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1OSbRqEgl6JtNYVhgu0ueze_ZgcYNzVQ',
    appId: '1:325148399429:web:a5939a54b9086e1572102c',
    messagingSenderId: '325148399429',
    projectId: 'krave-124',
    authDomain: 'krave-124.firebaseapp.com',
    storageBucket: 'krave-124.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjf_w0-Kfb0SGyXUA41xqPHkO4Tul6JKw',
    appId: '1:325148399429:android:8043a5577416c64672102c',
    messagingSenderId: '325148399429',
    projectId: 'krave-124',
    storageBucket: 'krave-124.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN5VSGzl7oKzX5mxCS12z14N_jI40JfiU',
    appId: '1:325148399429:ios:df08735632e87fe572102c',
    messagingSenderId: '325148399429',
    projectId: 'krave-124',
    storageBucket: 'krave-124.firebasestorage.app',
    iosBundleId: 'com.example.krave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN5VSGzl7oKzX5mxCS12z14N_jI40JfiU',
    appId: '1:325148399429:ios:df08735632e87fe572102c',
    messagingSenderId: '325148399429',
    projectId: 'krave-124',
    storageBucket: 'krave-124.firebasestorage.app',
    iosBundleId: 'com.example.krave',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1OSbRqEgl6JtNYVhgu0ueze_ZgcYNzVQ',
    appId: '1:325148399429:web:6a4a9ee9a10b4d1272102c',
    messagingSenderId: '325148399429',
    projectId: 'krave-124',
    authDomain: 'krave-124.firebaseapp.com',
    storageBucket: 'krave-124.firebasestorage.app',
  );
}
